config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'auth/google/callback',  to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get '/privacy', to: 'home#privacy'

  resources :home, only: [:index]
  resources :game, only: [:index]
  resources :user_games, only: [:new, :index, :show]
  resources :users, only: [:show]

  namespace :api do
    namespace :v1 do
      resources :user_games, only: [:create, :index, :update, :show, :destroy]
      resources :games, only: [:create]
      resources :users, only: [:show]
      resources :clues, only: [:create]
      resources :user_clues, only: [:destroy]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>TriviaHub</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="46Cmo65xmkn3HejWTL94pK2arhHoTvFeu7Mpfmf5dZ4" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <div class="navbar" id="navbar">
        <%= link_to "TriviaHub", home_index_path, class: "small-screen", id: "home-link" %>
        <%= link_to "Play", game_index_path %>
        <%= link_to "Browse", user_games_path %>
        <%= link_to "Create", new_user_game_path %>

        <div id="right-nav" class="right-nav">
          <%= link_to "Profile", user_path(current_user) %>
          <%= link_to "Sign Out", logout_path %>
        </div>
        <a class="icon small-screen">&#9776;</a>
      </div>

      <div class="top-panel">
        <div class = "row gutter" >
          <% if @user_game_new %>
            <h2 id=new-title>Create Your Own Game</h2>
            <h4 id=new-subtitle>Quiz other trivia buffs on topics you love.</h4>
          <% end %>

          <% if @user_games %>
            <h2 id=new-title>User-Created Games</h2>
            <h4 id=new-subtitle>Trebek isn't the only expert around here.</h4>
          <% end %>

          <% if @user_profile %>
            <h2 id=new-title>My Profile</h2>
          <% end %>

          <% if @game %>
            <h2 id=new-title>Classic Mode</h2>
          <% end %>

          <% if @user_game %>
            <h2 id=new-title><%= @user_game.title %></h2>
          <% end %>
        </div>
      </div>
    <% end %>

      <div class="layout-padding">

        <div class = "row gutter main">
          <% if flash %>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          <% end %>

          <%= yield %>
        </div>
      </div>

  </body>


</html>